[package]
name = "tun"
version = "0.1.0"
edition = "2024"

[dependencies]
smoltcp = { version = "0.14.0", default-features = false, features = [
    "std",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    "socket-tcp-reno",
] }
tokio = { version = "1.53.1", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
